### ISSUE TITLE
Issue with Linux

### ISSUE THREAD

**Issue by ArthurKnoep** [alfreddatakillen/ondeath#1]
Hi,

I don't know if this package is still maintained but after using it on a project, I can't get it to work on Linux.

You can find the source here: https://github.com/ArthurKnoep/radarr-emby-autoimporter/blob/feature/plex/src/autoImporter.js#L43

The callback function is not executed on my Ubuntu but it appears to be working on Windows 10

Ubuntu version: 19.10

**Comment by ArthurKnoep** [comment]
@thibautcornolti

**Comment by alfreddatakillen** [comment]
Hi! Arthur! Not sure why you run into that problem, I'm on linux only myself.

I do see that you do `const offDeath = onDeath( ...` etc. and then call `offDeath()`.
But, the `onDeath` function does not return anything, so you should get an `TypeError: offDeath is not a function` error on row 85, since `offDeath` should be `undefined`.

onDeath should still work, though...

Are you sure that your `start()` function is running at all?

**Comment by ArthurKnoep** [comment]
Hi thanks for your answer and sorry for the response time

I've actually opened my issue on the wrong repository :grinning:
The package used in the project is `death` and not yours (in my defense, it's not my code :smile:)

So sorry again and I close this issue

**Comment by alfreddatakillen** [comment]
hahah :)
